# Generated by Django 4.0.4 on 2022-05-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='access_token',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paste',
            name='delete_token',
            field=models.CharField(max_length=10),
        ),
    ]
